language: node_js

node_js:
  - "stable"

before_script:
  - echo "************************************ PRE BUILD SCRIPT **********************************"
  - cd ./deep-chess-engine
  - echo "****************************************************************************************"

after_script:
  - echo "************************************ POST BUILD SCRIPT *********************************"
  - echo "None"
  - echo "****************************************************************************************"
